-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.calendar
(
    service_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    monday boolean NOT NULL,
    tuesday boolean NOT NULL,
    wednesday boolean NOT NULL,
    thursday boolean NOT NULL,
    friday boolean NOT NULL,
    saturday boolean NOT NULL,
    sunday boolean NOT NULL,
    CONSTRAINT calendar_pkey PRIMARY KEY (service_id)
);

CREATE TABLE IF NOT EXISTS public.calendar_dates
(
    service_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    exception_type integer NOT NULL,
    CONSTRAINT calendar_dates_pkey PRIMARY KEY (service_id, date)
);

CREATE TABLE IF NOT EXISTS public.calendar_weekdays
(
    service_id character varying(10) COLLATE pg_catalog."default",
    weekday text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.calendar_weekends
(
    service_id character varying(10) COLLATE pg_catalog."default",
    weekend text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.fare_leg_rules
(
    leg_group_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    network_id character varying(20) COLLATE pg_catalog."default",
    fare_product_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fare_leg_rules_pkey PRIMARY KEY (leg_group_id, fare_product_id)
);

CREATE TABLE IF NOT EXISTS public.fare_products
(
    fare_product_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    fare_product_name character varying(100) COLLATE pg_catalog."default",
    amount numeric(5, 2) NOT NULL,
    currency character varying(3) COLLATE pg_catalog."default" NOT NULL,
    rider_category_id character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT fare_products_pkey PRIMARY KEY (fare_product_id)
);

CREATE TABLE IF NOT EXISTS public.fare_transfer_rules
(
    from_leg_group_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    to_leg_group_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    duration_limit integer,
    duration_limit_type integer,
    fare_transfer_type integer NOT NULL,
    transfer_count integer,
    CONSTRAINT fare_transfer_rules_pkey PRIMARY KEY (from_leg_group_id, to_leg_group_id)
);

CREATE TABLE IF NOT EXISTS public.rider_categories
(
    rider_category_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    rider_category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_default_fare_category integer NOT NULL,
    min_age integer,
    max_age integer,
    eligibility_url character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT rider_categories_pkey PRIMARY KEY (rider_category_id)
);

CREATE TABLE IF NOT EXISTS public.routes
(
    route_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    agency_id character varying(10) COLLATE pg_catalog."default",
    route_short_name character varying(50) COLLATE pg_catalog."default",
    route_long_name character varying(100) COLLATE pg_catalog."default",
    route_type integer NOT NULL,
    network_id character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT routes_pkey PRIMARY KEY (route_id)
);

CREATE TABLE IF NOT EXISTS public.shapes
(
    shape_id text COLLATE pg_catalog."default",
    shape_pt_lat double precision,
    shape_pt_lon double precision,
    shape_pt_sequence integer,
    shape_dist_traveled double precision
);

CREATE TABLE IF NOT EXISTS public.stop_times
(
    trip_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    stop_sequence integer NOT NULL,
    stop_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    arrival_time character varying(10) COLLATE pg_catalog."default",
    departure_time character varying(10) COLLATE pg_catalog."default",
    pickup_type integer,
    drop_off_type integer,
    timepoint integer,
    CONSTRAINT stop_times_pkey PRIMARY KEY (trip_id, stop_sequence)
);

CREATE TABLE IF NOT EXISTS public.stops
(
    stop_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    stop_name character varying(100) COLLATE pg_catalog."default",
    stop_lat numeric(9, 6) NOT NULL,
    stop_lon numeric(9, 6) NOT NULL,
    location_type integer,
    parent_station character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT stops_pkey PRIMARY KEY (stop_id)
);

CREATE TABLE IF NOT EXISTS public.trips
(
    trip_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    route_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    service_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    direction_id integer,
    block_id character varying(20) COLLATE pg_catalog."default",
    shape_id character varying(20) COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public.calendar_dates
    ADD CONSTRAINT calendar_dates_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.calendar (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fare_leg_rules
    ADD CONSTRAINT fare_leg_rules_fare_product_id_fkey FOREIGN KEY (fare_product_id)
    REFERENCES public.fare_products (fare_product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fare_products
    ADD CONSTRAINT fare_products_rider_category_id_fkey FOREIGN KEY (rider_category_id)
    REFERENCES public.rider_categories (rider_category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.stop_times
    ADD CONSTRAINT stop_times_stop_id_fkey FOREIGN KEY (stop_id)
    REFERENCES public.stops (stop_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trips
    ADD CONSTRAINT trips_route_id_fkey FOREIGN KEY (route_id)
    REFERENCES public.routes (route_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trips
    ADD CONSTRAINT trips_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.calendar (service_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;